# Numpy 연습문제

In [1]:
 import numpy as np

## 1번 길이가 10인 0-벡터를 만드세요.

In [2]:
test_array = np.zeros(10)
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 2번 길이가 10이며 다섯번 째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [3]:
np.eye(1,10, k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

## 3번 10부터 49까지의 값을 가지는 벡터를 만드세요.

In [4]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 4번 위(3번) 벡터의 순서를 바꾸세요.

In [5]:
a = np.arange(10,50)

reverse_a = np.flip(a)

reverse_a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 5번 0부터 8까지의 값을 가지는 3*3 행렬을 만드세요.

In [6]:
test_array = np.arange(0,9).reshape(3,3)
test_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 6번 벡터[1,2,0,0,4,0]에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [7]:
test_array = np.array([1,2,0,0,4,0])
test_array[test_array > 0]

array([1, 2, 4])

## 7번 3*3 단위 행렬을(identity matrix)을 만드세요

In [8]:
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 8번 난수 원소를 가지는 3*3 행렬을 만드세요

In [9]:
np.random.seed(seed=9)
np.random.uniform(0,1,9).reshape(3,3)

array([[0.01037415, 0.50187459, 0.49577329],
       [0.13382953, 0.14211109, 0.21855868],
       [0.41850818, 0.24810117, 0.08405965]])

## 9번 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [10]:
np.random.seed(seed=9)
a = np.random.uniform(0,1,9).reshape(3,3)
np.argmax(a), np.argmin(a)

(1, 0)

## 10번 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [11]:
np.random.seed(seed=9)
test_array = np.random.uniform(0,1,9).reshape(3,3)

test_array.mean(axis=1),test_array.mean(axis=0)

(array([0.33600735, 0.1648331 , 0.250223  ]),
 array([0.18757062, 0.29736228, 0.26613054]))